Add touch function
gamedev-js/input.js pull request #2
Opened 2017-10-26 03:15 UTC by cyy641278529

2017-10-26 10:22 UTC, jwu commented on index.js
> +const TOUCH_START = 0;
leave one new line

2017-10-26 10:24 UTC, jwu commented on index.js
> +  get touchID() {
no need for this function

2017-10-26 10:26 UTC, jwu commented on index.js
> +const TOUCH_PRESS = 1;
TOUCH_PRESSING

2017-10-27 02:36 UTC, jwu commented on examples/touchtest.html
> +  <script src="../dist/input.dev.js"></script>
move down

2017-10-27 02:36 UTC, jwu commented on examples/touchtest.html
> +  <script src="../node_modules/vconsole/dist/vconsole.min.js"></script>
move up.
We would like 3rd modules first

2017-10-27 02:37 UTC, jwu commented on examples/touchtest.html
> +  <script>
no need for this.

2017-10-27 02:39 UTC, jwu commented on index.js
> +      for (var i = 0; i < event.changedTouches.length; i++) {
var => let

2017-10-27 02:39 UTC, jwu commented on index.js
> +      for (var i = 0; i < this._touches.length; i++) {
var => let

2017-10-27 02:39 UTC, jwu commented on index.js
> +        for (var j = 0; j < event.changedTouches.length; j++) {
var => let

2017-10-27 02:40 UTC, jwu commented on index.js
> +            this._touches[i].y = event.changedTouches[j].clientY - this._bcr.left;
top

2017-10-27 02:40 UTC, jwu commented on index.js
> +        touch.prevY = touch.y = event.changedTouches[i].clientY - this._bcr.left;
top

2017-10-27 02:40 UTC, jwu commented on index.js
> +            this._touches[i].prevY = this._touches[i].y = event.changedTouches[j].clientY - this._bcr.left;
top

2017-10-27 02:41 UTC, jwu commented on index.js
> +      for (var i = 0; i < this._touches.length; i++) {
var => let

2017-10-27 02:41 UTC, jwu commented on index.js
> +        for (var j = 0; j < event.changedTouches.length; j++) {
var => let

2017-10-27 02:41 UTC, jwu commented on index.js
> +            this._touches[i].phase = TOUCH_END;
TOUCH_CANCEL

2017-10-27 02:41 UTC, jwu commented on index.js
> +    this._element.removeEventListener("touchstart", this._touchstartHandle);
one new line

2017-10-27 02:43 UTC, jwu requested changes

2017-10-27 02:43 UTC, jwu commented on index.js
> +      if (this._touches[i].phase === TOUCH_END) {
|| TOUCH_CANCEL

2017-10-27 02:44 UTC, jwu commented on package.json
> +    "uglify-es": "^3.0.15",
sort by name, thanks

2017-10-27 02:44 UTC, jwu commented on index.js
> +  get touchesList() {
touches

2017-10-27 03:33 UTC, jwu commented on examples/touchtest.html
> +          pos:${touch.x},${touch.y}
pos:[空格]

2017-10-27 03:34 UTC, jwu commented on examples/touchtest.html
> +          delta:${touch.dx},${touch.dy}
delta:$ {touch.dx}, ${touch.dy}

2017-10-27 03:34 UTC, jwu commented on examples/touchtest.html
> +          previous:${touch.prevX},${touch.prevY}
previous: ${touch.prevX}, ${touch.prevY}

2017-10-27 03:37 UTC, jwu commented on index.js
> +  * @property {array} touchesList
touchesList => touches

2017-10-27 03:38 UTC, jwu commented on index.js
> +  get mousePreviousX() {
mousePrevX

2017-10-27 03:38 UTC, jwu commented on index.js
> +   * @property {number} mouseDeltaX
mousePrevX

2017-10-27 03:38 UTC, jwu commented on index.js
> +   * @property {number} mouseDeltaY
mousePrevY

2017-10-27 03:38 UTC, jwu commented on index.js
> +  get mousePreviousY() {
mousePrevY

2017-10-27 03:44 UTC, jwu commented on examples/touchtest.html
> +  <!-- <script>
remove the code

2017-10-27 03:45 UTC, jwu commented on examples/touchtest.html
> +  <title>Example: Simple</title>
Example: Touches

2017-10-27 03:56 UTC, merged

2017-10-27 03:59 UTC, cyy641278529 commented
cocos-creator/engine-3d #125